import { Product } from './types';

export const products: Product[] = [
  { id: 'apple-mbp14-m4', brand: 'Apple', model: 'MacBook Pro 14 (M4)', cpu: 'Apple M4', ram: '16GB', storage: '512GB SSD', gpu: 'Integrated 10-core GPU', battery: 'Up to 18h', price: 8999, image: 'https://www.apple.com/v/macbook-pro/aq/images/overview/welcome/welcome_endframe__b7x5an4qzhuq_large.jpg', buyLink: 'https://www.apple.com/my/macbook-pro/', tags: ['cs', 'design'], portability: 8, performance: 10, batteryScore: 9, designScore: 9 },
  { id: 'apple-mba13-m3', brand: 'Apple', model: 'MacBook Air 13 (M3)', cpu: 'Apple M3', ram: '16GB', storage: '512GB SSD', gpu: 'Integrated 10-core GPU', battery: 'Up to 18h', price: 5999, image: 'https://www.apple.com/v/macbook-air/s/images/overview/hero/hero_static__c9sislzzicq6_large.jpg', buyLink: 'https://www.apple.com/my/macbook-air/', tags: ['business', 'general'], portability: 10, performance: 8, batteryScore: 10, designScore: 8 },
  { id: 'dell-xps-14', brand: 'Dell', model: 'XPS 14', cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD', gpu: 'NVIDIA RTX 4050', battery: 'Up to 13h', price: 9999, image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/page/consumer-family/xps-family/laptop/xps-14-9440/media-gallery/silver/notebook-xps-9440-t-sl-gallery-2.psd', buyLink: 'https://www.dell.com/en-my/shop/laptops/new-xps-14-laptop/spd/xps-14-9440-laptop', tags: ['design', 'cs'], portability: 8, performance: 9, batteryScore: 7, designScore: 9 },
  { id: 'asus-zephyrus-g14', brand: 'ASUS', model: 'ROG Zephyrus G14', cpu: 'AMD Ryzen 9', ram: '16GB', storage: '1TB SSD', gpu: 'NVIDIA RTX 4060', battery: 'Up to 10h', price: 8499, image: 'https://dlcdnwebimgs.asus.com/gain/3A3AB0A2-DB8B-4F44-92D4-00A0A31F8393/w1000/h732', buyLink: 'https://rog.asus.com/my/laptops/rog-zephyrus/rog-zephyrus-g14-2024/', tags: ['design', 'engineering'], portability: 7, performance: 10, batteryScore: 6, designScore: 8 },
  { id: 'huawei-matebook-x-pro', brand: 'Huawei', model: 'MateBook X Pro', cpu: 'Intel Core Ultra 9', ram: '16GB', storage: '1TB SSD', gpu: 'Intel Arc', battery: 'Up to 11h', price: 7999, image: 'https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/laptops/matebook-x-pro-2024/images/kv/matebook-x-pro-kv.png', buyLink: 'https://consumer.huawei.com/my/laptops/matebook-x-pro-2024/', tags: ['business', 'general'], portability: 9, performance: 8, batteryScore: 8, designScore: 9 },
  { id: 'lenovo-yoga-pro-9i', brand: 'Lenovo', model: 'Yoga Pro 9i', cpu: 'Intel Core Ultra 9', ram: '32GB', storage: '1TB SSD', gpu: 'NVIDIA RTX 4060', battery: 'Up to 9h', price: 9399, image: 'https://p4-ofp.static.pub/ShareResource/na/subseries/hero/lenovo-yoga-pro-9i-gen-9.png', buyLink: 'https://www.lenovo.com/my/en/p/laptops/yoga/yoga-pro-series/yoga-pro-9i-gen-9-16-inch-intel/len101y0048', tags: ['design', 'cs'], portability: 7, performance: 10, batteryScore: 6, designScore: 9 },
  { id: 'hp-spectre-x360', brand: 'HP', model: 'Spectre x360 14', cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD', gpu: 'Intel Arc', battery: 'Up to 14h', price: 7899, image: 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08296685.png', buyLink: 'https://www.hp.com/my-en/shop/laptops-tablets/personal-laptops/spectre-laptops.html', tags: ['business', 'general'], portability: 9, performance: 7, batteryScore: 8, designScore: 8 },
  { id: 'acer-swift-go-14', brand: 'Acer', model: 'Swift Go 14', cpu: 'Intel Core Ultra 5', ram: '16GB', storage: '512GB SSD', gpu: 'Intel Arc', battery: 'Up to 12h', price: 4699, image: 'https://store.acer.com/en-my/media/catalog/product/cache/4f688f4e4f3f1ad53f1308f6f90c7264/s/f/sfg14-73t_silver_01_1.jpg', buyLink: 'https://store.acer.com/en-my/acer-swift-go-14', tags: ['business', 'general', 'cs'], portability: 9, performance: 7, batteryScore: 8, designScore: 7 },
  { id: 'dell-inspiron-14', brand: 'Dell', model: 'Inspiron 14', cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD', gpu: 'Intel Iris Xe', battery: 'Up to 10h', price: 3999, image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/14-7440/media-gallery/notebook-inspiron-14-7440-t-laptop-gallery-2.psd', buyLink: 'https://www.dell.com/en-my/shop/laptops/inspiron-14-laptop/spd/inspiron-14-7440-laptop', tags: ['business', 'general'], portability: 8, performance: 6, batteryScore: 7, designScore: 6 }
];
